version: '2.28.1'
services:
  mongo-db-services1:
    image: mongo:5.0.27
    container_name: mongo-db-services1
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  mongo-express-services:
    image: mongo-express:1.0.2-18-alpine3.19
    restart: always
    container_name: mongo-express-services1
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-db-services1
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: admin #pass
      # ME_CONFIG_BASICAUTH: false #un hash in case i want to make a login without pass and useername
    ports:
      - 8081:8081 # http://localhost:8081 or http://0.0.0.0:8081
    volumes:  
      - ./data:/data/db
    depends_on:
      - mongo-db-services1
